### ISSUE TITLE
Updating to latest automation-client breaks integration tests

### ISSUE THREAD

**Issue by ddgenome** [atomist/spring-automation#40]
Upgrading to the latest automation-client breaks the Spring and Kotlin integrations tests. Locally I was able to fix the Spring one but I wasn't sure how to fix the Kotlin one, the target never appears to be set.

```
2018-05-18T13:40:12.760Z [m:73596] [info ]   1) Kotlin Spring5 generator integration test edits, verifies and compiles:
     TypeError: Cannot read property 'owner' of undefined
      at handle (node_modules/@atomist/automation-client/operations/generate/generatorToCommand.js:52:95)
      at FunctionWrappingCommandHandler.h (node_modules/@atomist/automation-client/operations/generate/generatorToCommand.js:48:16)
      at FunctionWrappingCommandHandler.handle (node_modules/@atomist/automation-client/onCommand.js:52:21)
      at generate (test/commands/generator/kotlin/KotlinSpring5IntegrationTest.ts:82:18)
      at Object.<anonymous> (test/commands/generator/kotlin/KotlinSpring5IntegrationTest.ts:59:33)
      at Generator.next (<anonymous>)
      at test/commands/generator/kotlin/KotlinSpring5IntegrationTest.ts:47:71
      at new WrappedPromise (node_modules/async-listener/es6-wrapped-promise.js:13:18)
      at __awaiter (test/commands/generator/kotlin/KotlinSpring5IntegrationTest.ts:27:12)
      at Context.it (test/commands/generator/kotlin/KotlinSpring5IntegrationTest.ts:58:46)

2018-05-18T13:40:12.760Z [m:73596] [info ]   2) spring generator integration test edits, verifies and compiles:
     TypeError: Cannot set property 'owner' of undefined
      at generate (test/commands/generator/spring/generatorIntegrationTest.ts:78:37)
      at Object.<anonymous> (test/commands/generator/spring/generatorIntegrationTest.ts:69:33)
      at Generator.next (<anonymous>)
      at test/commands/generator/spring/generatorIntegrationTest.ts:47:71
      at new WrappedPromise (node_modules/async-listener/es6-wrapped-promise.js:13:18)
      at __awaiter (test/commands/generator/spring/generatorIntegrationTest.ts:27:12)
      at Context.it (test/commands/generator/spring/generatorIntegrationTest.ts:60:46)
```

**Comment by ddgenome** [comment]
Merged in #41
